# Generated by Django 3.1.1 on 2020-09-15 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=50)),
                ('pregunta', models.TextField()),
                ('respuesta_a', models.TextField()),
                ('respuesta_b', models.TextField()),
                ('respuesta_c', models.TextField()),
                ('respuesta_d', models.TextField()),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('aciertos', models.IntegerField()),
                ('fallos', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
