# Generated by Django 3.1.1 on 2020-09-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='fallos',
            field=models.IntegerField(default=0),
        ),
    ]
